### ISSUE TITLE
How to deploy rocketmq to Windows system

### ISSUE THREAD

**Issue by cct668** [apache/rocketmq-connect#121]
If it can be deployed to Windows system, it will be convenient for testing, etc

**Comment by odbozhou** [comment]
https://rocketmq.apache.org/docs/quick-start/

**Comment by odbozhou** [comment]
https://rocketmq.apache.org/docs/quick-start/
You can take a look at the quick-start of rocketmq, there is a method for Windows to start rocketmq

**Comment by odbozhou** [comment]
Do you have any other questions?
