### ISSUE TITLE
The actual tag and key attributes of the message cannot be synchronized

### ISSUE THREAD

**Issue by zhangjidi2016** [apache/rocketmq-connect#127]
When a message is sent from the source cluster to the target cluster, the attributes of the synchronized message are prefixed with connect-ext-, causing the actual tag and key of the message to be lost.

![image](https://user-images.githubusercontent.com/18254437/167243252-776420cb-b2d3-4510-8df3-7b70af61fe54.png)

![image](https://user-images.githubusercontent.com/18254437/167243697-1d452486-a0ca-4f54-9f0c-1942ea9b912c.png)

**Comment by odbozhou** [comment]
Does this affect replicator synchronization messages?

**Comment by zhangjidi2016** [comment]
Message synchronization is not affected, message content can be properly synchronized，but the attributes of the message will be prefixed with connect-ext after synchronization, which will cause that the tag and key cannot be transmitted，see the screenshot above
