### ISSUE TITLE
集群部署时，BrokerBasedLog的消费模式是不是应该为广播模式，否则发送到MQ的配置，被自身消费，其他节点无法感知？

### ISSUE THREAD

**Issue by hellodake** [apache/rocketmq-connect#129]
原因：Node1发送的上线消息被自身消费，导致Node1无法感知到Node2上线。一旦就新的任务提交Reblance，检测到有两个节点上线，此时会均分任务，但是Node2本身就没有拿到配置信息，导致该由Node2执行的任务，没有运行。
![image](https://user-images.githubusercontent.com/30190232/167412700-9c32aaa7-2e6b-49b5-a4a0-4a1d4182ebd7.png)

**Comment by odbozhou** [comment]
订阅统一topic，使用不同的consumerGroup可以实现广播消费的。connect.conf中配置不同的wrokerId，启动不同的worker节点请配置不同的workerId。目前会使用workerId作为consumerGourp

**Comment by hellodake** [comment]
> 订阅统一topic，使用不同的consumerGroup可以实现广播消费的。connect.conf中配置不同的wrokerId，启动不同的worker节点请配置不同的workerId。目前会使用workerId作为consumerGourp

的确是因为wrokerId都是同一个导致的，感谢
