### ISSUE TITLE
Ensure the uniqueness of offset keys for different connectors

### ISSUE THREAD

**Issue by sunxiaojian** [apache/rocketmq-connect#143]
问题描述：

前提
connect-name-01，监听了 table-01，通过id增量查询数据，
connect-name-02，监听了 table-01，同时通过id增量查询数据

问题一：
如果两个任务用到的是一个组件；则两个任务的RecordPartition会重合，两个任务会公用，单任务不能完全处理所有的数据

问题二：
不通的组件间在相同的集群也会存在重合的可能，造成offset出现问题

**Comment by odbozhou** [comment]
merged
