### ISSUE TITLE
stop 和 delete api的一些问题

### ISSUE THREAD

**Issue by wongearl** [apache/rocketmq-connect#204]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
1. 掉用接口创建connector， http://xxxxxx/connectors/replicator-test-2?config={"connector-class":"org.apache.rocketmq.replicator.RmqSourceReplicator","source-rocketmq":"10.10.35.151:30891","target-rocketmq":"10.10.35.151:30891","replicator-store-topic":"replicator-store-topic","task-divide-strategy":"0","white-list":"testtopic","task-parallelism":"2","source-record-converter":"org.apache.rocketmq.connect.runtime.converter.JsonConverter","target-cluster":"DefaultCluster","source-cluster":"DefaultCluster","connect-topicname":"","topic.rename.format": "rename-${topic}"}

2. 调用接口http://xxxxx/connectors/replicator-test-2/stop ,停止connector
3. 调用接口http://xxxxxxxx/getConfigInfo ,查看找不到connector，stop是删除connector？
4.  调用接口 http://xxxxxxxxxx/connectors/replicator-test-2/delete , not found,接口未实现？

**Comment by sunxiaojian** [comment]
> **BUG REPORT**
> 
> 1. Please describe the issue you observed:
> 
> * What did you do (The steps to reproduce)?
> 
> 1. 掉用接口创建connector， [http://xxxxxx/connectors/replicator-test-2?config={"connector-class":"org.apache.rocketmq.replicator.RmqSourceReplicator","source-rocketmq":"10.10.35.151:30891","target-rocketmq":"10.10.35.151:30891","replicator-store-topic":"replicator-store-topic","task-divide-strategy":"0","white-list":"testtopic","task-parallelism":"2","source-record-converter":"org.apache.rocketmq.connect.runtime.converter.JsonConverter","target-cluster":"DefaultCluster","source-cluster":"DefaultCluster","connect-topicname":"","topic.rename.format](http://xxxxxx/connectors/replicator-test-2?config=%7B%22connector-class%22:%22org.apache.rocketmq.replicator.RmqSourceReplicator%22,%22source-rocketmq%22:%2210.10.35.151:30891%22,%22target-rocketmq%22:%2210.10.35.151:30891%22,%22replicator-store-topic%22:%22replicator-store-topic%22,%22task-divide-strategy%22:%220%22,%22white-list%22:%22testtopic%22,%22task-parallelism%22:%222%22,%22source-record-converter%22:%22org.apache.rocketmq.connect.runtime.converter.JsonConverter%22,%22target-cluster%22:%22DefaultCluster%22,%22source-cluster%22:%22DefaultCluster%22,%22connect-topicname%22:%22%22,%22topic.rename.format)": "rename-${topic}"}
> 2. 调用接口http://xxxxx/connectors/replicator-test-2/stop ,停止connector
> 3. 调用接口http://xxxxxxxx/getConfigInfo ,查看找不到connector，stop是删除connector？
> 4. 调用接口 http://xxxxxxxxxx/connectors/replicator-test-2/delete , not found,接口未实现？

delete接口已经移除，目前stop就是停止和移除任务， 后续api还会做进一步升级；

**Comment by wongearl** [comment]
@sunxiaojian 好的，谢谢
