### ISSUE TITLE
数据无法同步问题

### ISSUE THREAD

**Issue by zhangqiufeng88** [apache/rocketmq-connect#210]
1. 场景是使用rocketmq-opeartor部署了两个rocketmq集群A和B， 将rocketmq-connect容器化部署到集群与rocketmq集群A,B相同的k8s集群中，需求是将rocketmq集群A中的topic同步到rocket集群B. 
部署rocketmq-connect时connector-cluster-topic,connector-config-topic,connector-position-topic,connector-offset-topic,replicator-store-topic 这几个topic在集群B已创建
2. rocketmq-connect配置文件是：
# rockermq-connect-runtime-config

workerId=standalone-worker
storePathRootDir=/rocketmq-connect/storeRoot

## Http port for user to access REST API
httpPort=8082

# Rocketmq namesrvAddr
namesrvAddr={集群B的namesrvAddr}

# RocketMQ acl
aclEnable=false
accessKey=rocketmq
secretKey=12345678

#autoCreateGroupEnable=false
clusterName="rocketmqB"

# Source or sink connector jar file dir,The default value is rocketmq-connect-sample
pluginPaths=/rocketmq-connect/connectors/rocketmq-replicator/target/rocketmq-replicator-0.1.0-SNAPSHOT-jar-with-dependencies.jar

3.发送请求给rocketmq-runtime,请求内容：
http://{runtimeip}:{runtime-port}/connectors/replicator-test?config={"connector-class":"org.apache.rocketmq.replicator.RmqSourceReplicator","source-rocketmq":"{集群A的namesrvAddr}","target-rocketmq":"{集群B的namesrvAddr}","replicator-store-topic":"replicatorTopic","task-divide-strategy":"0","white-list":"test-2","task-parallelism":"2","source-record-converter":"org.apache.rocketmq.connect.runtime.converter.JsonConverter","target-cluster":"rocketmqB","source-cluster":"rocketmqA","connect-topicname":"","topic.rename.format": "rename-${topic}"}
4. 看日志，在集群A和B已成功注册生产者，runtime日志也显示已经连接A,B的broker成功，问题是，topic没有成功从A同步到B集群。

**Comment by sunxiaojian** [comment]
> 1. 场景是使用rocketmq-opeartor部署了两个rocketmq集群A和B， 将rocketmq-connect容器化部署到集群与rocketmq集群A,B相同的k8s集群中，需求是将rocketmq集群A中的topic同步到rocket集群B.
>    部署rocketmq-connect时connector-cluster-topic,connector-config-topic,connector-position-topic,connector-offset-topic,replicator-store-topic 这几个topic在集群B已创建
> 2. rocketmq-connect配置文件是：
> 
> # rockermq-connect-runtime-config
> workerId=standalone-worker storePathRootDir=/rocketmq-connect/storeRoot
> 
> ## Http port for user to access REST API
> httpPort=8082
> 
> # Rocketmq namesrvAddr
> namesrvAddr={集群B的namesrvAddr}
> 
> # RocketMQ acl
> aclEnable=false accessKey=rocketmq secretKey=12345678
> 
> #autoCreateGroupEnable=false clusterName="rocketmqB"
> 
> # Source or sink connector jar file dir,The default value is rocketmq-connect-sample
> pluginPaths=/rocketmq-connect/connectors/rocketmq-replicator/target/rocketmq-replicator-0.1.0-SNAPSHOT-jar-with-dependencies.jar
> 
> 3.发送请求给rocketmq-runtime,请求内容： http://{runtimeip}:{runtime-port}/connectors/replicator-test?config={"connector-class":"org.apache.rocketmq.replicator.RmqSourceReplicator","source-rocketmq":"{集群A的namesrvAddr}","target-rocketmq":"{集群B的namesrvAddr}","replicator-store-topic":"replicatorTopic","task-divide-strategy":"0","white-list":"test-2","task-parallelism":"2","source-record-converter":"org.apache.rocketmq.connect.runtime.converter.JsonConverter","target-cluster":"rocketmqB","source-cluster":"rocketmqA","connect-topicname":"","topic.rename.format": "rename-${topic}"} 4. 看日志，在集群A和B已成功注册生产者，runtime日志也显示已经连接A,B的broker成功，问题是，topic没有成功从A同步到B集群。

converter 配置有误，改成 "source-record-converter":"org.apache.rocketmq.connect.runtime.converter.JsonConverter",

**Comment by zhangqiufeng88** [comment]
> 

@sunxiaojian converter的配置跟你发的是一样的，是有其他地方写错吗

**Comment by sunxiaojian** [comment]
> > 
> 
> @sunxiaojian converter的配置跟你发的是一样的，是有其他地方写错吗

org.apache.rocketmq.connect.runtime.converter.record.json.JsonConverter   改成这个，我写错了

**Comment by python-chun** [comment]
使用RmqSourceReplicator，同步两个rocketmq集群(A,B)数据，只能将worker的nameSrv指定为B集群，并且task任务中source-rocketmq是A集群，target-rocketmq是B集群，这样部署吗？也就是只能source不能sink。当我把task任务中source-rocketmq改为B集群和target-rocketmq改为A集群，数据就不同步了；或者把worker的nameSrv指定为A集群，同样消息也不同步了。
请问如何实现sink的方式，因为我打算将A集群的消息同步给B集群和C集群，如果按照source的实现，我需要在B和C分别部署runtime worker才能实现。

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `bug` | Status: **Needs Info (Stale)**

This reports a data sync failure, but the description lacks sufficient detail to reproduce or diagnose the issue (no connector type, configuration, error logs, or version info).

Open since July 2022. Please provide reproduction details if this is still an issue.

---
*Automated evaluation by RockteMQ-AI*
