### ISSUE TITLE
Optimize plugin loading cloass loader, and support rest API to get connector plugin list

### ISSUE THREAD

**Issue by sunxiaojian** [apache/rocketmq-connect#230]
1. Add the loading type of converter and transform plug-ins
2. Add plug-in repeatability verification
3. Provide rest API to get the list of plug-ins

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `enhancement` | Status: **Evaluated**

This is a well-scoped enhancement with three clear objectives:
1. Add loading support for converter and transform plugins
2. Add plugin repeatability verification (prevent duplicate loading)
3. Provide REST API to query the plugin list

**Feasibility:** Feasible — builds on the existing plugin loading infrastructure.
**Scope:** Plugin classloader, REST API layer
**Compatibility:** Additive changes; existing plugins should continue to work.

Note: PR #232 appears to address this issue.

---
*Automated evaluation by github-manager*
