### ISSUE TITLE
FileSourceConnector cannot send data to a topic specified in RocketMQ

### ISSUE THREAD

**Issue by sunxi92** [apache/rocketmq-connect#25]
**BUG REPORT**

1. Please describe the issue you observed:

When I test the demo rocketmq-connect-sample, I find that there is no data in the topic fileTopic.

- What did you do (The steps to reproduce)?

follow the link:
https://rocketmq-1.gitbook.io/rocketmq-connector/quick-start/runtime-qs
https://rocketmq-1.gitbook.io/rocketmq-connector/quick-start/file-connector

- What is expected to see?
(1)The topic fileTopic have the data
(2)FileSinkConnector can transfer data to specified file

- What did you see instead?
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/25401190/159831635-b0003b43-8ae7-4dd2-87be-52dda4dc8110.png">

3. Please tell us about your environment:

4. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**Comment by odbozhou** [comment]
Can you describe in detail how it happened? Configuration of FileSourceConnector, using branch of rocketmq-connect ?

**Comment by sunxi92** [comment]
> Can you describe in detail how it happened? Configuration of FileSourceConnector, using branch of rocketmq-connect ?
I follow the following steps to operate：
(1)Start a RocketMQ cluster and create  the topic  fileTopic
(2)Build the project
(3)Update the connect.conf, include storePathRootDir、pluginPaths
![image](https://user-images.githubusercontent.com/25401190/160065252-618d0238-2806-44b9-b0b4-9aec6344a74f.png)
(4)Copy rocketmq-connect-sample-0.0.1-SNAPSHOT.jar to pluginPaths
(5)Prepare  the  source data
(6)Run run_worker.sh 
(7)Start the source connector:
http://127.0.0.1:8082/connectors/fileConnectorSource?config={
"connector-class":"org.apache.rocketmq.connect.file.FileSourceConnector",
"topic":"fileTopic",
"filename":"/Users/sunxi/Documents/application/rocketmq-connect/source-file/source-file.txt",
"source-record-converter":"org.apache.rocketmq.connect.runtime.converter.JsonConverter"
}   
The console information is as follows:
INFO qtp624271064-23 - config: {"connector-class":"org.apache.rocketmq.connect.file.FileSourceConnector","topic":"fileTopic","filename":"/Users/sunxi/Documents/application/rocketmq-connect/source-file/source-file.txt","source-record-converter":"org.apache.rocketmq.connect.runtime.converter.JsonConverter"}
(8)Start the sink connector:
  http://127.0.0.1:8082/connectors/fileConnectorSink?config={
    "connector-class":"org.apache.rocketmq.connect.file.FileSinkConnector",
    "topicNames":"fileTopic",
    "filename":"/Users/sunxi/Documents/application/rocketmq-connect/source-file/sink-file.txt",
    "source-record-converter":"org.apache.rocketmq.connect.runtime.converter.JsonConverter"
 }
The console information is as follows:
INFO qtp624271064-20 - config: {"connector-class":"org.apache.rocketmq.connect.file.FileSinkConnector","topicNames":"fileTopic","filename":"/Users/sunxi/Documents/application/rocketmq-connect/source-file/sink-file.txt","source-record-converter":"org.apache.rocketmq.connect.runtime.converter.JsonConverter"}

The results are as follow:
(1)The topic fileTopic has no data
(2)Since there is no data in topic fileTopic, the data is not transferred to the specified file

**Comment by odbozhou** [comment]
Please update the latest master code, this issue has been resolved. However, due to the upgrade of the api. The latest code has solved this problem.
Please install the latest api, mvn install locally https://github.com/openmessaging/openconnect/pull/37

**Comment by sunxi92** [comment]
> Please update the latest master code, this issue has been resolved. However, due to the upgrade of the api. The latest code has solved this problem. Please install the latest api, mvn install locally [openmessaging/openconnect#37](https://github.com/openmessaging/openconnect/pull/37)
