### ISSUE TITLE
Hudi-sink-connector adapt to new api

### ISSUE THREAD

**Issue by lizhiboo** [apache/rocketmq-connect#256]

**Comment by ShannonDing** [comment]
close due to #257

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `type/enhancement` | Status: **Evaluated**

Hudi sink connector adaptation to new API is a necessary enhancement to maintain compatibility with the connector framework's evolving API surface.

**Feasibility:** Feasible — API migration task.
**Scope:** hudi-sink-connector module.
**Compatibility:** Internal adaptation, no user-facing breaking changes expected.

---
*Automated evaluation by github-manager*
