### ISSUE TITLE
Schema Inferencing for JsonConverter

### ISSUE THREAD

**Issue by odbozhou** [apache/rocketmq-connect#385]
在很多情况，发送到RocketMQ Topic的消息是没有schema信息的，例如大部分业务消息，业务开发者之间一般通过接口文档的方式描述topic中的消息数据格式，这些数据一般是json，下游根据接口文档的描述对topic中的数据解析，转换成类对象。

connector实现是通用的，通过简单的配置化即可使用，如果没有schema信息，sink connector可能很难解析topic中的数据。

但是由于json数据的特殊性，我们可以根据json数据简单的反推数据的schema
例如
{
 "id": 10000,
 "name": "connector",
 "create_datetime": 1501834166000,
 "update_timestamp": 1501834166000
}
我们可以推断出对应的schema
{
 "schema": {
 "type": "struct",
 "fields": [{
 "type": "int32",
 "optional": true,
 "field": "id"
 }, {
 "type": "string",
 "optional": true,
 "field": "name"
 }, {
 "type": "int64",
 "optional": false,
 "name": "org.apache.rocketmq.connect.data.Timestamp",
 "version": 1,
 "field": "create_datetime"
 }, {
 "type": "int64",
 "optional": false,
 "name": "org.apache.rocketmq.connect.data.Timestamp",
 "version": 1,
 "field": "update_timestamp"
 }],
 "optional": false,
 "name": "user"
 },
 "payload": {
 "id": 10000,
 "name": "connector",
 "create_datetime": 1501834166000,
 "update_timestamp": 1501834166000
}
}

根据上面的例子，基本可以判断
JsonConverter可以通过简单的数据推断出起对应你的schema
推断出schema后对sink connector处理数据是十分有用的

**Comment by joeCarf** [comment]
我希望能领取这个task。我应该从哪部分代码入手呢？

**Comment by joeCarf** [comment]
> 在很多情况，发送到RocketMQ Topic的消息是没有schema信息的，例如大部分业务消息，业务开发者之间一般通过接口文档的方式描述topic中的消息数据格式，这些数据一般是json，下游根据接口文档的描述对topic中的数据解析，转换成类对象。
> 
> connector实现是通用的，通过简单的配置化即可使用，如果没有schema信息，sink connector可能很难解析topic中的数据。
> 
> 但是由于json数据的特殊性，我们可以根据json数据简单的反推数据的schema 例如 { "id": 10000, "name": "connector", "create_datetime": 1501834166000, "update_timestamp": 1501834166000 } 我们可以推断出对应的schema { "schema": { "type": "struct", "fields": [{ "type": "int32", "optional": true, "field": "id" }, { "type": "string", "optional": true, "field": "name" }, { "type": "int64", "optional": false, "name": "org.apache.rocketmq.connect.data.Timestamp", "version": 1, "field": "create_datetime" }, { "type": "int64", "optional": false, "name": "org.apache.rocketmq.connect.data.Timestamp", "version": 1, "field": "update_timestamp" }], "optional": false, "name": "user" }, "payload": { "id": 10000, "name": "connector", "create_datetime": 1501834166000, "update_timestamp": 1501834166000 } }
> 
> 根据上面的例子，基本可以判断 JsonConverter可以通过简单的数据推断出起对应你的schema 推断出schema后对sink connector处理数据是十分有用的

hi, I'd liked to do it. But i may need some help. Where should i start from?

**Comment by joeCarf** [comment]
and could you plz assign this issue to me? thanks a lot @odbozhou

**Comment by joeCarf** [comment]
hi, 我想知道我目前应该重点关注哪些文件呢？以及目前仓库中有哪些我可以参考的内容吗

> > and could you plz assign this issue to me? thanks a lot @odbozhou
> 
> If you encounter any problems now, you can raise them in this issue, and I can provide some targeted help

**Comment by joeCarf** [comment]
经过熟悉JsonConverter这部分的代码，我理解我之后的工作应该集中于这部分
![1669999190813](https://user-images.githubusercontent.com/52153761/205341732-8fae4678-cb45-4711-91fb-1b3b059f5719.jpg)
当schemasEnabled()为false时，应该进行json解析以生成schema。

这个思路和方向是否正确？麻烦您有时间点拨一下，thx～ @odbozhou

**Comment by joeCarf** [comment]
hi，我大概整理出了一个设计流程图，想和您讨论一下：
![Schema Inferencing for JsonConverter](https://user-images.githubusercontent.com/52153761/206893015-dc5e386d-a649-4175-89be-52af21250928.png)

由于单纯的json数据中所携带的信息量比较少，只能通过人为制定规则来进行填充schema；我制定了一些规则：
1. 对于schema里的optional字段，直接置为false
2. 对于schema的name字段，默认置为“default”或者null
3. 当原json中有多个数据的时候，schema的type置为“struct”；当json中只有一个数据时，schema的type使用json数据的type
4. 对于schema中的name、version等字段，不好进行推断，不知道您是否有一些建议
5. 对于某个数据字段的type，我只能通过JSONObject.value的所属类来判断，例如{"id": 10000}中的value instanceof Integer，因此认为schema.type=int32。这样做的弊端在于比较粗略，不能保证推断出来的type是完全正确的，同时对于一些特殊的字段类型如struct、map、date等处理起来可能会比较麻烦

**Comment by joeCarf** [comment]
> 

希望您能给一些建议～ @odbozhou
