### ISSUE TITLE
compact topic support

### ISSUE THREAD

**Issue by odbozhou** [apache/rocketmq-connect#397]
目前connect的offset，config，status元数据信息都存在普通topic中，
无法根据key进行元数据进行压缩，元数据较多时可能产生性能问题
最新版本的rocketmq已经支持compact topic，可以解决此问题
需要将普通topic替换成compact topic支持提升性能

**Comment by sunxiaojian** [comment]
https://github.com/apache/rocketmq-connect/issues/352
