### ISSUE TITLE
配置服务rocketmq实现疑问

### ISSUE THREAD

**Issue by leehom** [apache/rocketmq-connect#505]
配置服务local和rocketmq实现可以用于分布式环境，但两者有个重要差别，START_SIGNAL的分发，local实现start的时候发出START_SIGNAL，获取其他worker节点的配置，这样，在负载均衡过程中获取connector/task的配置，但rocketmq并没有START_SIGNAL，怎么获取全量的connector/task的配置？

**Comment by leehom** [comment]
> 配置变化时会向指定的配置topic（connector-config-topic）发消息 可以看下这块实现 org.apache.rocketmq.connect.runtime.service.AbstractConfigManagementService#putConnectorConfig
> 
> 所有worker都会消费connector-config-topic消息。这样所有worker就可以获取到全量的connector，task配置信息 处理逻辑可以看下这个方法 org.apache.rocketmq.connect.runtime.service.AbstractConfigManagementService#process

你说的这个我知道，那是变更的时候，我说的场景时，一个新的worker启动，local服务发START_SIGNAL，让其他worker发送自身的配置，新的worker得到全量的配置，但rocketmq实现并没有发送START_SIGNAL，新worker是怎么样获取全量的配置？

**Comment by leehom** [comment]
> > 配置变化时会向指定的配置topic（connector-config-topic）发消息 可以看下这块实现 org.apache.rocketmq.connect.runtime.service.AbstractConfigManagementService#putConnectorConfig
> > 所有worker都会消费connector-config-topic消息。这样所有worker就可以获取到全量的connector，task配置信息 处理逻辑可以看下这个方法 org.apache.rocketmq.connect.runtime.service.AbstractConfigManagementService#process
> 
> 你说的这个我知道，那是变更的时候，我说的场景时，一个新的worker启动，local服务发START_SIGNAL，让其他worker发送自身的配置，新的worker得到全量的配置，但rocketmq实现并没有发送START_SIGNAL，新worker是怎么样获取全量的配置？

我估计是还没实现类似kafka connect的KafkaBackingStore

**Comment by sunxiaojian** [comment]
> KafkaBackingStore

org.apache.rocketmq.connect.runtime.utils.datasync.BrokerBasedLog

**Comment by leehom** [comment]
> > KafkaBackingStore
> 
> org.apache.rocketmq.connect.runtime.utils.datasync.BrokerBasedLog

明白，还是要补一下rocketmq
