### ISSUE TITLE
配置服务rocketmq实现的疑问

### ISSUE THREAD

**Issue by leehom** [apache/rocketmq-connect#506]
配置服务的rocketmq实现start并没有发出START_SIGNAL，获取其他worker的配置，local实现是有的，rocketmq实现不支持新worker负载均衡？

**Comment by leehom** [comment]
> ClusterManagementServiceImpl

ClusterManagementServiceImpl成员变更发现，然后就重分派，新的worker需要知道全量的连接器和任务配置，local实现通过发送START_SIGNAL，获取其他worker的配置，但rocketmq实现并没有，不知道怎么获取全量的连接器和任务配置

**Comment by leehom** [comment]
> > ClusterManagementServiceImpl
> 
> ClusterManagementServiceImpl成员变更发现，然后就重分派，新的worker需要知道全量的连接器和任务配置，local实现通过发送START_SIGNAL，获取其他worker的配置，但rocketmq实现并没有，不知道怎么获取全量的连接器和任务配置

位点也有同样的问题，位点的local实现ONLINE的事件进行新旧worker 偏移的同步，rocketmq没有

**Comment by sunxiaojian** [comment]
rocketmq是为 rocketmq compact topic准备的，用的是一个topic 存储的，不需要进行通知，监听compact就行了
