### ISSUE TITLE
WorkerDirectTask put position may partially store information lost

### ISSUE THREAD

**Issue by Slideee** [apache/rocketmq-connect#90]
For the method of sendRecord in WorkerDirectTask, there may be multiple sets of RecordPartition and RecordOffset in sourceDataEntries, so these two variables should be inside the loop body and can be stored by Map. At present, writing this way will cause these two variables to be overwritten all the time, resulting in partial The storage of the offset is abnormal

![image](https://user-images.githubusercontent.com/48793283/163302628-79c5ac01-0b78-4159-bf39-ae733e447dac.png)

For example, if a topic has 4 queues that need to be synchronized, then only the offset of one of the queues is stored at the end

![B96E3A9160F5529AB86AA31AA0F91F36](https://user-images.githubusercontent.com/48793283/163511658-a3729732-1a01-4a44-b44a-fad469e7ff53.jpg)
![image](https://user-images.githubusercontent.com/48793283/163511669-f2b3686f-b7b4-4426-b7d9-6f268439163f.png)

after repair

![image](https://user-images.githubusercontent.com/48793283/163511778-d858c2cc-e443-4501-9588-b23a58c55cb1.png)

**Comment by Slideee** [comment]
@odbozhou can you take a look at this question? In addition, is there any plan to adapt the new api of replicator? If no one does, I will do it.

**Comment by odbozhou** [comment]
> @odbozhou can you take a look at this question? In addition, is there any plan to adapt the new api of replicator? If no one does, I will do it.

I saw the pr that your replicator adapts to the latest connect api, it's great

**Comment by odbozhou** [comment]
merged
